#! /bin/bash

USAGE="USAGE:  src/main/shell/create-syntax-test testname 'full text query' expected_results"
TESTDIR=src/test

TESTNAME=$1
QUERY=$2
EXPECTED_COUNT=$3

[ -z "${TESTNAME}" ] && echo "${USAGE}" && exit 1
[ -z "${QUERY}" ] && echo "${USAGE}" && exit 1
[ -z "${EXPECTED_COUNT}" ] && echo "${USAGE}" && exit 1

if [ -f "${TESTDIR}/sql/${TESTNAME}.sql" ] ; then
	echo "${TESTNAME} already exists"
	exit 1
fi

echo "SELECT assert(count(*), ${EXPECTED_COUNT}, '${TESTNAME}') FROM so_posts WHERE zdb('so_posts', ctid) ==> '${QUERY}';" > ${TESTDIR}/sql/${TESTNAME}.sql

if [ ! -f "${TESTDIR}/expected/${TESTNAME}.out" ] ; then
    rm -f results/${TESTNAME}.out
    TEST="${TESTNAME}" make installcheck &> /tmp/create-test.log

    grep -q "ERROR:" results/${TESTNAME}.out
    if [ $? == 0 ] ; then
        # the test contained an error
        cat results/${TESTNAME}.out

        rm ${TESTDIR}/sql/${TESTNAME}.sql
        exit 1;
    fi

    # copy the expected output file
    cp results/${TESTNAME}.out ${TESTDIR}/expected/

    # run the test again
    TEST="${TESTNAME}" make installcheck

    if [ "$?" != "0" ] ; then
        echo ERROR CREATING NEW TEST
        exit 1
    fi

    # ad the test to the list of tests to run
    echo "${TESTNAME}" >> ${TESTDIR}/tests.list

    git add ${TESTDIR}/sql/${TESTNAME}.sql ${TESTDIR}/expected/${TESTNAME}.out ${TESTDIR}/tests.list
else
    echo "expected/${TESTNAME}.out already exists!"
    exit 1
fi
