/* Generated By:JJTree: Do not edit this line. ASTArray.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package llc.zombodb.query_parser;

public
class ASTArray extends QueryParserNode {

  private Iterable<Object> externalValues;
  private int totalExternalValues;
  private boolean isAnd = false;

  public ASTArray(int id) {
    super(id);
  }

  public ASTArray(QueryParser p, int id) {
    super(p, id);
  }

  public boolean isAnd() {
    return isAnd;
  }

  public void setAnd(boolean isAnd) {
    this.isAnd = isAnd;
  }

  public boolean hasExternalValues() {
    return externalValues != null;
  }

  public Iterable<Object> getExternalValues() {
    return externalValues;
  }

  public void setExternalValues(Iterable<Object> values, int total) {
    externalValues = values;
    totalExternalValues = total;
  }

  public int getTotalExternalValues() {
    return totalExternalValues;
  }

    @Override
  public String toString() {
    return super.toString() + " (" + (isAnd() ? "AND" : "OR") + ((hasExternalValues()) ? "; values=" + externalValues : "") + ")";
  }

    public String getDescription() {
        return fieldname + " " + operator + " " + getChildValues();
    }

  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=56ceb80f079b7f22192e50c292859aea (do not edit this line) */
