/* Generated By:JJTree: Do not edit this line. ASTJsonAgg.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package llc.zombodb.query_parser;

public
class ASTJsonAgg extends ASTAggregate {
  public ASTJsonAgg(int id) {
    super(id);
  }

  public ASTJsonAgg(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=72fcc7f1624b30ac19d8a07ba38058c1 (do not edit this line) */
