/* Generated By:JJTree: Do not edit this line. ASTLimit.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package llc.zombodb.query_parser;

import java.util.ArrayList;
import java.util.List;

public
class ASTLimit extends QueryParserNode {
  public static class Sorts {
    public final String fieldname;
    public final String direction;

    private Sorts(String fieldname, String direction) {
      this.fieldname = fieldname;
      this.direction = direction;
    }
  }
  public ASTLimit(int id) {
    super(id);
  }

  public ASTLimit(QueryParser p, int id) {
    super(p, id);
  }


  public List<Sorts> getSorts() {
    List<Sorts> l = new ArrayList<>();

    for (int i=0; i<jjtGetNumChildren()-2; i+=2) {
      l.add(new Sorts(String.valueOf(getChild(i).getValue()), String.valueOf(getChild(i+1).getValue())));
    }
    return l;
  }

  public int getOffset() {
    return Integer.valueOf(String.valueOf(getChild(jjtGetNumChildren()-2).getValue()));
  }

  public int getLimit() {
    return Integer.valueOf(String.valueOf(getChild(jjtGetNumChildren()-1).getValue()));
  }


  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=47810319df365d1b799e53febb39a350 (do not edit this line) */
