/* Generated By:JJTree: Do not edit this line. ASTIndexLink.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tcdi.zombodb.query_parser;

public class ASTIndexLink extends com.tcdi.zombodb.query_parser.QueryParserNode {

    public static ASTIndexLink create(final String leftFieldname, final String indexName, final String rightFieldname) {
        ASTIndexLink link = new ASTIndexLink(QueryParserTreeConstants.JJTINDEXLINK);

        ASTLeftField left = new ASTLeftField(QueryParserTreeConstants.JJTLEFTFIELD);
        left.setValue(leftFieldname);
        link.jjtAddChild(left, 0);

        ASTIndexName index = new ASTIndexName(QueryParserTreeConstants.JJTINDEXNAME);
        index.setValue(indexName);
        link.jjtAddChild(index, 1);

        ASTRightField right = new ASTRightField(QueryParserTreeConstants.JJTRIGHTFIELD);
        right.setValue(rightFieldname);
        link.jjtAddChild(right, 2);

        return link;
    }

    public ASTIndexLink(int id) {
        super(id);
    }

    public ASTIndexLink(QueryParser p, int id) {
        super(p, id);
    }

    public boolean hasFieldname() {
        return getFieldname() != null;
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(QueryParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public String getLeftFieldname() {
        return jjtGetNumChildren() == 0 ? null : String.valueOf(getChild(0).value);
    }

    public String getIndexName() {
        return jjtGetNumChildren() == 0 ? null : String.valueOf(getChild(1).value);
    }

    public String getRightFieldname() {
        return jjtGetNumChildren() == 0 ? null : String.valueOf(getChild(2).value);
    }

    public void qualifyIndexName(String prefix) {
        getChild(1).value = prefix + "." + getChild(1).value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();

        sb.append(getLeftFieldname()).append("=<").append(getIndexName()).append(">").append(getRightFieldname());

        if (hasFieldname()) {
            sb.insert(0, getFieldname() + ":(");
            sb.append(")");
        }
        return sb.toString();
    }
}
/* JavaCC - OriginalChecksum=a599e1b5e1384d114e4c82bc47a5f71a (do not edit this line) */
