/* Generated By:JJTree: Do not edit this line. ASTNestedGroup.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tcdi.zombodb.query_parser;

public
class ASTNestedGroup extends com.tcdi.zombodb.query_parser.QueryParserNode {
  protected boolean isAnd = false;

  public ASTNestedGroup(int id) {
    super(id);
  }

  public ASTNestedGroup(QueryParser p, int id) {
    super(p, id);
  }

  public boolean isAnd() {
    return isAnd;
  }

  public void setAnd(boolean isAnd) {
    this.isAnd = isAnd;
  }

  public String getNestedPath() {
    return fieldname;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ed29f520b4a3146911bc5ace39868da1 (do not edit this line) */
