/* Generated By:JJTree: Do not edit this line. ASTRangeAggregate.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tcdi.zombodb.query_parser;

public
class ASTRangeAggregate extends ASTAggregate {
  public ASTRangeAggregate(int id) {
    super(id);
  }

  public ASTRangeAggregate(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  public String getRangeSpec() {
    return getChild(0).getValue().toString();
  }
}
/* JavaCC - OriginalChecksum=8028058fa988d1760326a973a79022ec (do not edit this line) */
