/* Generated By:JJTree: Do not edit this line. ASTTally.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.tcdi.zombodb.query_parser;

public
class ASTTally extends ASTAggregate {
  public ASTTally(int id) {
    super(id);
  }

  public ASTTally(QueryParser p, int id) {
    super(p, id);
  }


  public String getStem() {
    return String.valueOf(getChild(0).getValue());
  }

  public int getMaxTerms() {
    return Integer.valueOf(String.valueOf(getChild(1).getValue()));
  }

  public String getSortOrder() {
    return String.valueOf(getChild(2).getValue());
  }

  public int getShardSize() {
    Object child = getChild(3);
    if (child instanceof ASTNumber)
      return Integer.valueOf(String.valueOf(((ASTNumber) child).getValue()));
    else
      return 0;
  }
  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9cecf607a634dc6027616a996a968ca2 (do not edit this line) */
